#!/usr/bin/env bash

echo "["
awk "
{
    printf \"{'name': '%s', 'os': %d, 'embedded': %d, 'relay': %d, 'sport': %d, 'ai': %d, 'functional': %d, 'ml': %d, 'security': %d, 'swe': %d, 'theory': %d, 'mirego': %d, 'bell': %d, 'olympus': %d, 'cse-cts': %d, 'ALL': 0},\n\",
    \$1, \$2, \$3, \$4, \$5, \$6, \$7, \$8, \$9, \$10, \$11, \$12, \$13, \$14, \$15
}
" SPREADSHEET
echo "]"
